
authors:
  sdargoeuves:
    name: Seb
    description: Net[any]Ops noodler
    # avatar: assets/logo.svg # NoodleOps logo
    # avatar: https://github.com/sdargoeuves.png # Perso GitHub profile picture
    avatar: https://github.com/sebastien-dargoeuves-ipf.png # IPF GitHub profile picture
    # avatar: https://ugc.production.linktr.ee/91fa8ed7-0886-46f6-8e84-01eef99e30b6_profile-clear-bckgnd.jpeg?io=true&size=avatar # Linktr.ee profile picture
    # url: https://noodleops.com